version: '3'
services:
  ghost:
      image: ghost:latest
      restart: always
      environment:
        url: http://techlore.tech
        database__client: mysql
        database__connection__host: db
        database__connection__user: root
        database__connection__password: your_database_root_password
        database__connection__database: ghost
      volumes:
        - /opt/ghost_content:/var/lib/ghost/content

  db:
      image: mysql:5.7
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: your_database_root_password
      volumes:
        - /opt/ghost_mysql:/var/lib/mysql

  nginx:
      build:
        context: ./nginx
      restart: always
      ports:
        - "80:80"
        - "443:443"
      volumes:
         - /etc/letsencrypt/:/etc/letsencrypt/
         - /usr/share/nginx/html:/usr/share/nginx/html

  static: 
    image: rbreeze/techlore
    ports: 
      - "8080:8080"